services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
        - ./php_code/:/var/www/html/

  php:
    build: ./php_code/
    expose:
      - 9000
    volumes:
      - ./php_code/:/var/www/html/

  db:    
    image: mariadb  
    volumes: 
      - ./mariadb-data:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
    environment:  
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: notes
      MYSQL_USER: user
      MYSQL_PASSWORD: password